food = input("Name a Food > ")
plant = input("Name a type of plant > ")
method = input("Name a method of cooking > ")
print()
burned = input("What word describes burned food? > ")
item = input("Name a DIY item > ")
print()
print("MENU")
print(method, food, "with", burned, plant, "on a bed of", item)
